name: AI Weekly Digest

on:
  schedule:
    - cron: '0 9 * * 1'  # 每周一 09:00 UTC 运行（北京时间周一傍晚）
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python fetch_and_summarize.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekly_digest
          path: output/weekly_digest.md
